esphome:
  name: "${name}"
  friendly_name: Air Quality Sensor
  comment: DIY Air Quality Sensor
  name_add_mac_suffix: true

  project:
    name: "DIY.AirQuality-1"
    version: "${version}"

  min_version: 2024.6.4

dashboard_import:
  package_import_url: github://KrzysztofHajdamowicz/air-quality-sensor/ESPHome/AirQuality-1.yaml
  import_full_config: false

improv_serial:

logger:

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:
    ssid: "DIY AirQuality-1 Hotspot"

packages:
  remote_package:
    url: https://github.com/KrzysztofHajdamowicz/air-quality-sensor/
    ref: main
    files:
      - ESPHome/Core.yaml
    refresh: 0d
