substitutions:
  name: airquality-1
  version: "1.0.0"
  device_description: ${name} DIY Sensor - version ${version}.

esphome:
  name: ${device_name}
  board: d1_mini
  platform: ESP8266

api:
logger:
captive_portal:
web_server:
  port: 80

uart:
  rx_pin: D7
  tx_pin: D8
  baud_rate: 9600

i2c:
  - id: bus_a
    sda: D2
    scl: D1

sensor:
  - platform: senseair
    co2:
      name: "CO2 Value"
      filters:
        - filter_out: 0
    update_interval: 60s
    id: senseair_sensor
  - platform: sps30
    pm_1_0: &sps30sensortemplate
      name: "PM <1µm Weight concentration"
      id: "PM_1_0"
      unit_of_measurement: "µg/m³"
      device_class: "pm1"
      state_class: "measurement"
      accuracy_decimals: 1
      disabled_by_default: true
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: "PM_2_5"
      <<: *sps30sensortemplate
      device_class: "pm25"
      disabled_by_default: false
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: "PM_4_0"
      <<: *sps30sensortemplate
      device_class: "pm1"
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: "PM_10_0"
      <<: *sps30sensortemplate
      device_class: "pm10"
      disabled_by_default: false
    pm_size:
      name: "Typical Particle size"
      id: "pm_size"
      state_class: "measurement"
      unit_of_measurement: "µm"
    address: 0x69
    update_interval: 60s
  - platform: uptime
    name: Uptime


button:
  - platform: template
    id: calibrate_senseair
    name: Calibrate SenseAir
    on_press:
      then:
        - logger.log: Starting calibration of SenseAir S8. Assuming device is in well ventillated area to baseline 400ppm
        - senseair.background_calibration: senseair_sensor
  - platform: restart
    name: "Restart"
